title: Ninghui Feng's Homepage
page-top-title: Ninghui Feng
top-section-bg-text: Computer Science
home-subtitle: Ninghui Feng&ensp;|&ensp;冯宁辉
copyright-text: '&copy; Ninghui Feng 2023-2024. All Rights Reserved.'
